services:
  - type: web
    name: digital-inspector-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn back.app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SUMMARIZE_MODE
        value: counts
